CREATE TABLE IF NOT EXISTS northwind.categories (
    category_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS northwind.suppliers (
    supplier_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    contact_name TEXT,
    contact_title TEXT,
    city TEXT,
    region TEXT,
    country TEXT,
    phone TEXT
);

CREATE TABLE IF NOT EXISTS northwind.customers (
    customer_id CHAR(5) PRIMARY KEY,
    company_name TEXT NOT NULL,
    contact_name TEXT,
    contact_title TEXT,
    city TEXT,
    region TEXT,
    country TEXT,
    phone TEXT,
    fax TEXT
);

CREATE TABLE IF NOT EXISTS northwind.employees (
    employee_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name TEXT NOT NULL,
    first_name TEXT NOT NULL,
    title TEXT,
    title_of_courtesy TEXT,
    birth_date DATE,
    hire_date DATE,
    city TEXT,
    region TEXT,
    country TEXT,
    reports_to SMALLINT REFERENCES northwind.employees (employee_id)
);

CREATE TABLE IF NOT EXISTS northwind.shippers (
    shipper_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name TEXT NOT NULL,
    phone TEXT
);

CREATE TABLE IF NOT EXISTS northwind.products (
    product_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    supplier_id SMALLINT REFERENCES northwind.suppliers (supplier_id),
    category_id SMALLINT REFERENCES northwind.categories (category_id),
    quantity_per_unit TEXT,
    unit_price NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
    units_in_stock SMALLINT NOT NULL DEFAULT 0 CHECK (units_in_stock >= 0),
    units_on_order SMALLINT NOT NULL DEFAULT 0 CHECK (units_on_order >= 0),
    reorder_level SMALLINT NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
    discontinued BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS northwind.orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id CHAR(5) REFERENCES northwind.customers (customer_id),
    employee_id SMALLINT REFERENCES northwind.employees (employee_id),
    order_date DATE,
    required_date DATE,
    shipped_date DATE,
    ship_via SMALLINT REFERENCES northwind.shippers (shipper_id),
    freight NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (freight >= 0),
    ship_name TEXT,
    ship_city TEXT,
    ship_region TEXT,
    ship_country TEXT
);

CREATE TABLE IF NOT EXISTS northwind.order_details (
    order_id INTEGER NOT NULL REFERENCES northwind.orders (order_id) ON DELETE CASCADE,
    product_id SMALLINT NOT NULL REFERENCES northwind.products (product_id),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    quantity SMALLINT NOT NULL CHECK (quantity > 0),
    discount NUMERIC(4, 3) NOT NULL DEFAULT 0 CHECK (discount >= 0 AND discount <= 1),
    PRIMARY KEY (order_id, product_id)
);

CREATE TABLE IF NOT EXISTS northwind.regions (
    region_id SMALLINT PRIMARY KEY,
    region_description TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS northwind.territories (
    territory_id TEXT PRIMARY KEY,
    territory_description TEXT NOT NULL,
    region_id SMALLINT NOT NULL REFERENCES northwind.regions (region_id)
);

CREATE TABLE IF NOT EXISTS northwind.employee_territories (
    employee_id SMALLINT NOT NULL REFERENCES northwind.employees (employee_id) ON DELETE CASCADE,
    territory_id TEXT NOT NULL REFERENCES northwind.territories (territory_id) ON DELETE CASCADE,
    PRIMARY KEY (employee_id, territory_id)
);

