INSERT INTO analytics.schema_metadata (
    table_schema, table_name, column_name, description, sample_values, semantic_type, is_sensitive
) VALUES
    ('northwind', 'customers', 'customer_id', 'Stable five-character customer identifier used across orders.', '["ALFKI", "QUICK", "SAVEA"]', 'identifier', FALSE),
    ('northwind', 'customers', 'company_name', 'Customer company or account name.', '["Alfreds Futterkiste", "QUICK-Stop", "Save-a-lot Markets"]', 'dimension', FALSE),
    ('northwind', 'customers', 'country', 'Customer billing country for geographic segmentation.', '["Germany", "USA", "France"]', 'geo', FALSE),
    ('northwind', 'orders', 'order_id', 'Primary order identifier.', '[10248, 10400, 11011]', 'identifier', FALSE),
    ('northwind', 'orders', 'customer_id', 'Customer associated with the order.', '["ALFKI", "WOLZA", "QUICK"]', 'foreign_key', FALSE),
    ('northwind', 'orders', 'employee_id', 'Sales employee responsible for the order.', '[1, 3, 5]', 'foreign_key', FALSE),
    ('northwind', 'orders', 'order_date', 'Date when the order was placed.', '["1996-07-04", "1997-01-01", "1998-04-09"]', 'date', FALSE),
    ('northwind', 'orders', 'freight', 'Freight charge associated with shipment.', '[32.38, 83.93, 1.21]', 'measure', FALSE),
    ('northwind', 'order_details', 'unit_price', 'Unit price captured at order time.', '[14.00, 21.00, 81.00]', 'measure', FALSE),
    ('northwind', 'order_details', 'quantity', 'Number of units sold on the order line.', '[5, 20, 60]', 'measure', FALSE),
    ('northwind', 'order_details', 'discount', 'Line-level discount rate between 0 and 1.', '[0, 0.05, 0.15]', 'measure', FALSE),
    ('northwind', 'products', 'product_id', 'Stable product identifier.', '[1, 11, 35]', 'identifier', FALSE),
    ('northwind', 'products', 'product_name', 'Commercial product name.', '["Chai", "Queso Cabrales", "Steeleye Stout"]', 'dimension', FALSE),
    ('northwind', 'products', 'category_id', 'Product category foreign key.', '[1, 4, 8]', 'foreign_key', FALSE),
    ('northwind', 'products', 'unit_price', 'Current product list price.', '[18.00, 38.00, 97.00]', 'measure', FALSE),
    ('northwind', 'categories', 'category_name', 'Product category such as Beverages or Seafood.', '["Beverages", "Dairy Products", "Seafood"]', 'dimension', FALSE),
    ('analytics', 'query_log', 'prompt', 'Natural language request submitted by a user or agent.', '["Top products by revenue", "Sales by country"]', 'text', FALSE),
    ('analytics', 'query_log', 'generated_sql', 'SQL generated by the AI assistant before execution.', '["SELECT ..."]', 'sql', FALSE),
    ('analytics', 'schema_metadata', 'sample_values', 'JSON array of representative values for model grounding and UI hints.', '[["Germany", "USA"], [10248, 10400]]', 'metadata', FALSE)
ON CONFLICT (table_schema, table_name, column_name) DO UPDATE
SET
    description = EXCLUDED.description,
    sample_values = EXCLUDED.sample_values,
    semantic_type = EXCLUDED.semantic_type,
    is_sensitive = EXCLUDED.is_sensitive,
    updated_at = NOW();

